import Link from "next/link";

export default function Home() {
  return (
    <main className="min-h-screen bg-[#090909] text-[#f5f4f1]">
      <section className="relative isolate min-h-[84svh] overflow-hidden border-b border-white/10 px-5 py-7 sm:px-10">
        <video className="absolute inset-0 -z-20 h-full w-full object-cover object-[65%_center] grayscale contrast-125 brightness-[.55]" autoPlay muted loop playsInline preload="metadata" poster="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/tmjnuDhpwrWwdDyk.jpg" aria-label="Multitud en una fiesta nocturna, video ambiental sin sonido"><source src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/GbHXpGORdFcoZgeV.mp4" type="video/mp4" /></video>
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(9,9,9,.96)_0%,rgba(9,9,9,.75)_35%,rgba(9,9,9,.23)_70%,rgba(9,9,9,.45)_100%)]" />
        <div className="pointer-events-none absolute inset-0 -z-10 opacity-20" style={{ backgroundImage: "radial-gradient(#f5f4f1 0.65px, transparent 0.65px)", backgroundSize: "5px 5px" }} />
        <img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/DhFdaRxXMNUlLvfQ.png" alt="" className="pointer-events-none absolute -right-12 top-1/2 -z-10 w-[min(58vw,560px)] -translate-y-1/2 rotate-[-7deg] opacity-[.075] grayscale brightness-200" />
        <nav className="mx-auto flex max-w-7xl items-center justify-between"><span className="text-lg font-black italic tracking-[-.08em]">ANC<br />TICKETS</span><Link href="/login" className="rounded-full border border-white/30 bg-black/25 px-4 py-2 text-xs font-bold tracking-[.14em] backdrop-blur-sm transition hover:border-[#b695ff] hover:text-[#b695ff]">INGRESAR</Link></nav>
        <div className="mx-auto flex min-h-[68vh] max-w-7xl flex-col justify-end pb-10"><p className="text-xs font-bold tracking-[.28em] text-[#c3adff]">ACCESO / MÚSICA / BUENAS VIBRAS</p><h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.82] tracking-[-.09em] sm:text-8xl lg:text-9xl">ANC<br /><span className="text-[#a77fff]">TICKETS</span></h1><p className="mt-7 max-w-md text-base leading-7 text-neutral-200">La plataforma para crear, vender y vivir noches que dejan marca.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/login" className="rounded-xl bg-[#a77fff] px-5 py-3 text-sm font-black text-black transition hover:bg-[#c6b0ff]">CREAR MI EVENTO →</Link><Link href="/login" className="rounded-xl border border-white/30 bg-black/20 px-5 py-3 text-sm font-bold backdrop-blur-sm transition hover:border-white">INGRESAR A MI PANEL</Link></div></div>
      </section>
      <section className="mx-auto grid max-w-7xl gap-px bg-white/10 md:grid-cols-3"><article className="bg-[#090909] p-7"><p className="text-xs font-bold tracking-[.2em] text-[#a77fff]">01 / PRODUCTORES</p><h2 className="mt-4 text-2xl font-black tracking-[-.05em]">Crea la noche<br />sin formularios.</h2><p className="mt-4 text-sm leading-6 text-neutral-400">Seis decisiones guiadas, borrador automático y un preview vivo de tu evento.</p></article><article className="bg-[#090909] p-7"><p className="text-xs font-bold tracking-[.2em] text-[#a77fff]">02 / PÚBLICO</p><h2 className="mt-4 text-2xl font-black tracking-[-.05em]">Accede con<br />una entrada clara.</h2><p className="mt-4 text-sm leading-6 text-neutral-400">Compra, QR y tu entrada en un solo recorrido pensado para móvil.</p></article><article className="bg-[#090909] p-7"><p className="text-xs font-bold tracking-[.2em] text-[#a77fff]">03 / PUERTA</p><h2 className="mt-4 text-2xl font-black tracking-[-.05em]">Control en<br />tiempo real.</h2><p className="mt-4 text-sm leading-6 text-neutral-400">Staff por evento, validación atómica y protección contra dobles ingresos.</p></article></section>
    </main>
  );
}
