import Link from "next/link";

const events = [
  { label: "Sáb 18 Oct · 23:59", title: "After Party / Vol. 12", venue: "Club Mistral", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/FkDMkRzDjwcxsHMI.jpg", featured: true },
  { label: "Vie 24 Oct · 22:30", title: "Nocturna 04", venue: "Nido Club", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/odnSxdePQnJFmYhJ.jpg", featured: false },
  { label: "Sáb 01 Nov · 00:00", title: "Línea Viva", venue: "Sala Ámbar", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/sJWyjPBFsNofukrp.jpg", featured: false },
];

export default function Home() {
  return (
    <main className="min-h-screen bg-[#090909] text-[#f5f4f1]">
      <section className="relative isolate min-h-[84svh] overflow-hidden border-b border-white/10 px-5 py-7 sm:px-10">
        <video className="absolute inset-0 -z-20 h-full w-full object-cover object-[65%_center] grayscale contrast-125 brightness-[.55]" autoPlay muted loop playsInline preload="metadata" poster="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/tmjnuDhpwrWwdDyk.jpg" aria-label="Multitud en una fiesta nocturna, video ambiental sin sonido"><source src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/GbHXpGORdFcoZgeV.mp4" type="video/mp4" /></video>
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(9,9,9,.96)_0%,rgba(9,9,9,.75)_35%,rgba(9,9,9,.23)_70%,rgba(9,9,9,.45)_100%)]" />
        <div className="pointer-events-none absolute inset-0 -z-10 opacity-20" style={{ backgroundImage: "radial-gradient(#f5f4f1 0.65px, transparent 0.65px)", backgroundSize: "5px 5px" }} />
        <img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/DhFdaRxXMNUlLvfQ.png" alt="" className="pointer-events-none absolute -right-12 top-1/2 -z-10 w-[min(58vw,560px)] -translate-y-1/2 rotate-[-7deg] opacity-[.075] grayscale brightness-200" />
        <div className="mx-auto flex min-h-[73vh] max-w-7xl flex-col justify-end pb-10"><p className="text-xs font-bold tracking-[.28em] text-[#c3adff]">ACCESO / MÚSICA / BUENAS VIBRAS</p><h1 className="mt-5 max-w-4xl text-6xl font-black leading-[.82] tracking-[-.09em] sm:text-8xl lg:text-9xl">ANC<br /><span className="text-[#a77fff]">TICKETS</span></h1><p className="mt-7 max-w-md text-base leading-7 text-neutral-200">La plataforma para crear, vender y vivir noches que dejan marca.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/login" className="rounded-xl bg-[#a77fff] px-5 py-3 text-sm font-black text-black transition hover:bg-[#c6b0ff]">CREAR MI EVENTO →</Link><a href="#eventos" className="rounded-xl border border-white/30 bg-black/20 px-5 py-3 text-sm font-bold backdrop-blur-sm transition hover:border-white">VER PRÓXIMOS EVENTOS</a></div><div className="mt-14 flex items-center gap-3 text-xs font-bold tracking-[.18em] text-white/70"><span className="h-px w-16 bg-[#a77fff]" />TU NOCHE EMPIEZA AQUÍ</div></div>
      </section>
      <section id="eventos" className="mx-auto max-w-7xl px-5 py-20 sm:px-10"><div className="mb-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.25em] text-[#a77fff]">AGENDA ABIERTA</p><h2 className="mt-3 text-5xl font-black leading-[.84] tracking-[-.08em] sm:text-7xl">PRÓXIMOS<br />EVENTOS.</h2></div><p className="max-w-sm text-sm leading-6 text-neutral-400">Una selección editorial de noches por descubrir. Las fechas son una vista de demostración de la experiencia ANC.</p></div><div className="grid gap-3 md:grid-cols-3">{events.map((event) => <article key={event.title} className={`group relative min-h-[420px] overflow-hidden border border-white/10 bg-[#121212] p-6 ${event.featured ? "md:min-h-[520px]" : ""}`}><img src={event.image} alt="" className="absolute inset-0 h-full w-full object-cover grayscale contrast-125 transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/45 to-transparent" /><div className="absolute inset-3 border border-[#a77fff] opacity-0 transition group-hover:opacity-100" /><div className="relative flex h-full flex-col justify-end"><p className="text-xs font-bold tracking-[.16em] text-[#c3adff]">{event.label}</p><h3 className="mt-3 text-3xl font-black leading-[.9] tracking-[-.06em]">{event.title}</h3><div className="mt-5 flex items-center justify-between text-xs text-neutral-300"><span>{event.venue}</span><Link href="/login" className="font-bold text-white transition group-hover:text-[#c3adff]">VER ENTRADAS ↗</Link></div></div></article>)}</div></section>
      <section id="organizadores" className="grid border-y border-white/10 bg-[#0d0d0d] lg:grid-cols-2"><div className="relative min-h-[540px] overflow-hidden"><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/ucGRmmUxeMRLDHAq.jpeg" alt="Pulsera ANC Tickets lila" className="h-full w-full object-cover object-center contrast-125" /><div className="absolute inset-0 bg-gradient-to-r from-transparent to-black/55" /></div><div className="flex flex-col justify-between p-8 sm:p-14"><div><p className="text-xs font-bold tracking-[.25em] text-[#a77fff]">PARA ORGANIZADORES</p><h2 className="mt-5 text-5xl font-black leading-[.85] tracking-[-.08em] sm:text-7xl">CREA LA<br /><span className="text-[#a77fff]">NOCHE.</span><br />CONTROLA LA<br />PUERTA.</h2></div><ol className="mt-12 space-y-5 text-sm text-neutral-300"><li className="grid grid-cols-[42px_1fr] gap-3 border-t border-white/15 pt-4"><strong className="text-[#a77fff]">01</strong><span>Construye tu evento en seis decisiones visuales, sin formularios interminables.</span></li><li className="grid grid-cols-[42px_1fr] gap-3 border-t border-white/15 pt-4"><strong className="text-[#a77fff]">02</strong><span>Abre una página que se siente como parte de la experiencia.</span></li><li className="grid grid-cols-[42px_1fr] gap-3 border-t border-white/15 pt-4"><strong className="text-[#a77fff]">03</strong><span>Invita a tu staff y valida cada acceso desde la puerta.</span></li></ol><Link href="/login" className="mt-10 inline-flex w-fit rounded-xl bg-[#f5f4f1] px-5 py-3 text-sm font-black text-black transition hover:bg-[#c6b0ff]">VER PANEL DE ORGANIZADOR →</Link></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-10"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-xs font-bold tracking-[.25em] text-[#a77fff]">UNA OPERACIÓN SIMPLE</p><h2 className="mt-4 text-5xl font-black leading-[.85] tracking-[-.08em] sm:text-7xl">TODO BAJO<br />CONTROL.</h2><p className="mt-7 max-w-lg text-base leading-7 text-neutral-400">El tono cambia de editorial a operativo cuando hay que vender o validar. La estética acompaña la información: nunca compite con ella.</p><div className="mt-12 grid gap-px border border-white/10 bg-white/10 sm:grid-cols-2">{[["01 / CREA","Diseña la página de tu fecha."],["02 / VENDE","Abre acceso al público."],["03 / RECIBE","Entrega un ticket claro."],["04 / VALIDA","Haz que la puerta fluya."]].map(([num, title]) => <div key={num} className="bg-[#090909] p-6"><p className="text-xs font-bold tracking-[.18em] text-[#a77fff]">{num}</p><h3 className="mt-4 text-2xl font-black leading-tight tracking-[-.04em]">{title}</h3></div>)}</div></div><div className="relative flex min-h-[520px] items-end overflow-hidden border border-white/10 bg-[#151515] p-8"><img src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663820533004/sJWyjPBFsNofukrp.jpg" alt="Ambiente nocturno de ANC Tickets" className="absolute inset-0 h-full w-full object-cover grayscale contrast-125" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-transparent" /><div className="relative max-w-xs"><p className="text-xs font-bold tracking-[.25em] text-[#c3adff]">TU TICKET, SIEMPRE CONTIGO</p><h3 className="mt-4 text-4xl font-black leading-[.88] tracking-[-.06em]">UNA NOCHE.<br />UN TICKET.</h3><p className="mt-5 text-sm leading-6 text-neutral-300">Compra, QR y acceso listos para la puerta.</p></div></div></div></section>
      <section className="border-t border-white/10 bg-[#a77fff] px-5 py-16 text-black sm:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs font-black tracking-[.25em]">ANC TICKETS / CHILE</p><h2 className="mt-4 text-6xl font-black leading-[.8] tracking-[-.1em] sm:text-8xl">ONE NIGHT.<br />ONE TICKET.</h2></div><div className="max-w-xs"><p className="text-base font-medium leading-6">Una presencia que capta eventos. Un producto que convierte acceso en control.</p><Link href="/login" className="mt-7 inline-flex rounded-xl bg-black px-5 py-3 text-sm font-black text-white transition hover:bg-white hover:text-black">CREAR MI EVENTO →</Link></div></div></section>
      <footer className="flex flex-col gap-3 border-t border-white/10 px-5 py-7 text-xs font-bold tracking-[.12em] text-neutral-500 sm:flex-row sm:justify-between sm:px-10"><span>ANC TICKETS</span><span>BLANCO / NEGRO / PULSO ANC</span><span>CHILE</span></footer>
    </main>
  );
}
