import { desc, eq } from "drizzle-orm";
import OrganizerNav from "@/components/organizer-nav";
import { db } from "@/lib/db";
import { discountCodes, events } from "@/lib/db/schema";
import { requireOrganizationManager } from "@/lib/organizer";
import { createDiscountCode } from "../../actions";

export default async function PromotionsPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { organization } = await requireOrganizationManager(slug);
  const organizerEvents = await db.select().from(events).where(eq(events.organizationId, organization.id));
  const codes = await db.select({ code: discountCodes, eventTitle: events.title }).from(discountCodes).innerJoin(events, eq(events.id, discountCodes.eventId)).where(eq(events.organizationId, organization.id)).orderBy(desc(discountCodes.createdAt));
  return <div><OrganizerNav slug={slug} /><h1 className="text-2xl font-bold">Promociones</h1><p className="mt-1 text-sm text-neutral-600">Un código por compra, con límite de uso y vigencia controlados.</p><section className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{codes.length === 0 ? <p className="rounded-xl border border-dashed border-neutral-300 p-5 text-sm text-neutral-500">Aún no tienes códigos de descuento.</p> : codes.map(({ code, eventTitle }) => <article key={code.id} className="flex items-center justify-between rounded-xl border border-neutral-200 p-4"><div><p className="font-semibold">{code.code}</p><p className="text-sm text-neutral-500">{eventTitle} · {code.type === "percentage" ? `${code.value}%` : `$${code.value}`} · {code.isActive ? "Activo" : "Pausado"}</p></div></article>)}</div><form action={createDiscountCode} className="h-fit rounded-xl border border-neutral-200 bg-neutral-50 p-5"><h2 className="font-semibold">Crear código</h2><input type="hidden" name="slug" value={slug} /><div className="mt-4 grid gap-3"><select required name="eventId" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm"><option value="">Selecciona un evento</option>{organizerEvents.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select><input required name="code" placeholder="Código visible" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input name="internalName" placeholder="Nombre interno" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><select name="type" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm"><option value="percentage">Porcentaje</option><option value="fixed">Monto fijo</option></select><input required name="value" type="number" min="0" step="0.01" placeholder="Valor" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input name="maxRedemptions" type="number" min="1" placeholder="Límite total (opcional)" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input name="maxPerBuyer" type="number" min="1" defaultValue="1" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><button className="rounded-lg bg-neutral-950 px-4 py-2 text-sm font-semibold text-white">Crear código</button></div></form></section></div>;
}
