"use client";

import { useMemo, useState } from "react";
import { createImmersiveEvent } from "@/app/dashboard/organizer/actions";

const moods = [
  ["Música", "♫", "Club, concierto, festival"],
  ["Cultura", "◐", "Arte, cine, conversación"],
  ["Deporte", "↗", "Partido, carrera, encuentro"],
  ["Comunidad", "✦", "Taller, feria, experiencia"],
  ["Otro", "＋", "Hazlo tuyo"],
];

const steps = ["Intención", "Tiempo", "Acceso", "Ventas", "Visual", "Final"];

export default function EventCreatorWizard({ slug, lastEvent }: { slug: string; lastEvent?: { title: string; category: string | null; venue: string | null; description: string | null; imageUrl: string | null } | null }) {
  const [step, setStep] = useState(0);
  const [category, setCategory] = useState("Música");
  const [title, setTitle] = useState("");
  const [eventDate, setEventDate] = useState("");
  const [venue, setVenue] = useState("");
  const [accessMode, setAccessMode] = useState<"single" | "presale" | "custom">("single");
  const [saleMode, setSaleMode] = useState<"now" | "scheduled">("now");
  const [description, setDescription] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const canMove = useMemo(() => [Boolean(title.trim() && category), Boolean(eventDate && venue.trim()), true, saleMode === "now" || Boolean(eventDate), true, true][step], [step, title, category, eventDate, venue, saleMode]);
  const next = () => canMove && setStep((current) => Math.min(current + 1, 5));
  const previous = () => setStep((current) => Math.max(current - 1, 0));
  const jump = (target: number) => target <= step && setStep(target);

  return <form action={async (formData) => { setIsSubmitting(true); await createImmersiveEvent(formData); }} className="relative min-h-[calc(100vh-9rem)] overflow-hidden rounded-[2rem] bg-[#090909] p-5 text-[#f5f4f1] shadow-2xl sm:p-8">
    <input type="hidden" name="slug" value={slug} /><input type="hidden" name="category" value={category} /><input type="hidden" name="title" value={title} /><input type="hidden" name="eventDate" value={eventDate} /><input type="hidden" name="venue" value={venue} /><input type="hidden" name="accessMode" value={accessMode} /><input type="hidden" name="saleMode" value={saleMode} /><input type="hidden" name="description" value={description} /><input type="hidden" name="imageUrl" value={imageUrl} />
    <div className="pointer-events-none absolute inset-0 opacity-25" style={{ backgroundImage: "radial-gradient(#9b6cff 0.65px, transparent 0.65px)", backgroundSize: "5px 5px" }} />
    <div className="relative grid min-h-[calc(100vh-13rem)] gap-8 lg:grid-cols-[minmax(0,1fr)_340px]">
      <div className="flex min-w-0 flex-col"><header className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[.28em] text-[#b695ff]">ANC / CREAR LA NOCHE</p><p className="mt-1 text-sm text-neutral-400">Borrador guardado mientras avanzas.</p></div><span className="rounded-full border border-white/15 px-3 py-1 text-xs text-neutral-300">{step + 1} / 6</span></header>
        <nav className="mt-8 flex gap-2 overflow-x-auto pb-1" aria-label="Progreso de creación">{steps.map((label, index) => <button key={label} type="button" onClick={() => jump(index)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-semibold transition ${index === step ? "bg-[#9b6cff] text-black" : index < step ? "bg-white/10 text-white" : "text-neutral-500"}`}>{label}</button>)}</nav>
        <div className="flex flex-1 flex-col justify-center py-10">
          {step === 0 && <section className="max-w-2xl"><p className="text-sm font-medium text-[#b695ff]">01 — INTENCIÓN</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">¿Qué experiencia<br />estás creando?</h1>{lastEvent && <button type="button" onClick={() => { setCategory(lastEvent.category ?? "Música"); setTitle(`${lastEvent.title} — nueva edición`); setVenue(lastEvent.venue ?? ""); setDescription(lastEvent.description ?? ""); setImageUrl(lastEvent.imageUrl ?? ""); }} className="mt-5 rounded-full border border-[#9b6cff]/60 bg-[#9b6cff]/10 px-4 py-2 text-xs font-bold text-[#c8b6ff] transition hover:bg-[#9b6cff]/20">↻ Repetir mi último evento</button>}<div className="mt-7 grid gap-3 sm:grid-cols-2">{moods.map(([name, icon, copy]) => <button type="button" key={name} onClick={() => setCategory(name)} className={`flex items-center gap-4 rounded-2xl border p-4 text-left transition ${category === name ? "border-[#9b6cff] bg-[#9b6cff]/15" : "border-white/15 bg-white/[.03] hover:border-white/40"}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-xl text-[#b695ff]">{icon}</span><span><strong className="block text-sm">{name}</strong><small className="text-xs text-neutral-400">{copy}</small></span></button>)}</div><label className="mt-8 block text-sm font-medium text-neutral-300">¿Cómo se llama esta experiencia?<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ej. After Party Vol. 12" className="mt-3 w-full border-b border-white/30 bg-transparent py-3 text-2xl font-semibold outline-none placeholder:text-neutral-600 focus:border-[#9b6cff]" /></label></section>}
          {step === 1 && <section className="max-w-xl"><p className="text-sm font-medium text-[#b695ff]">02 — TIEMPO Y LUGAR</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">¿Cuándo y dónde<br />ocurre todo?</h1><div className="mt-8 grid gap-4"><label className="text-sm font-medium text-neutral-300">Fecha y hora<input value={eventDate} onChange={(event) => setEventDate(event.target.value)} type="datetime-local" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white outline-none focus:border-[#9b6cff]" /></label><label className="text-sm font-medium text-neutral-300">Recinto o dirección<input value={venue} onChange={(event) => setVenue(event.target.value)} placeholder="Ej. Club Mistral, Santiago" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white outline-none placeholder:text-neutral-600 focus:border-[#9b6cff]" /></label></div></section>}
          {step === 2 && <section className="max-w-2xl"><p className="text-sm font-medium text-[#b695ff]">03 — ACCESO</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">¿Cómo entra<br />tu público?</h1><div className="mt-7 grid gap-3 md:grid-cols-3">{[["single", "Una entrada", "Un acceso, un precio."], ["presale", "Preventa + general", "Dos momentos de venta."], ["custom", "Personalizado", "Comienza con una entrada."]].map(([value, heading, copy]) => <button type="button" key={value} onClick={() => setAccessMode(value as typeof accessMode)} className={`rounded-2xl border p-4 text-left transition ${accessMode === value ? "border-[#9b6cff] bg-[#9b6cff]/15" : "border-white/15 bg-white/[.03] hover:border-white/40"}`}><strong className="block text-sm">{heading}</strong><small className="mt-1 block text-xs text-neutral-400">{copy}</small></button>)}</div>{accessMode === "presale" ? <div className="mt-6 grid gap-3 sm:grid-cols-2"><TicketFields prefix="presale" label="Preventa" /><TicketFields prefix="general" label="General" /></div> : <div className="mt-6 max-w-md"><label className="block text-sm font-medium text-neutral-300">Nombre de entrada<input name="ticketName" defaultValue={accessMode === "custom" ? "Acceso" : "Entrada general"} className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white" /></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-medium text-neutral-300">Valor<input required name="ticketPrice" min="1" type="number" placeholder="12000" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white" /></label><label className="text-sm font-medium text-neutral-300">Cupos<input required name="ticketCapacity" min="1" type="number" placeholder="150" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white" /></label></div></div>}<p className="mt-5 text-xs text-neutral-500">No hay entradas sin valor. Los accesos especiales se administran después, con cupos y comisión adicional.</p></section>}
          {step === 3 && <section className="max-w-xl"><p className="text-sm font-medium text-[#b695ff]">04 — RITMO DE VENTA</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">¿Cuándo se abre<br />la puerta digital?</h1><div className="mt-8 grid gap-3">{[["now", "Abrir ahora", "Tu borrador queda listo para revisión ANC."], ["scheduled", "Programar apertura", "Elige cuándo aparecen las entradas."]].map(([value, heading, copy]) => <button type="button" key={value} onClick={() => setSaleMode(value as typeof saleMode)} className={`rounded-2xl border p-5 text-left transition ${saleMode === value ? "border-[#9b6cff] bg-[#9b6cff]/15" : "border-white/15 bg-white/[.03] hover:border-white/40"}`}><strong>{heading}</strong><small className="mt-1 block text-neutral-400">{copy}</small></button>)}</div>{saleMode === "scheduled" && <label className="mt-5 block text-sm font-medium text-neutral-300">Apertura de ventas<input required name="salesStart" type="datetime-local" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white" /></label>}</section>}
          {step === 4 && <section className="max-w-xl"><p className="text-sm font-medium text-[#b695ff]">05 — PULSO VISUAL</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">Dale una cara<br />a la noche.</h1><div className="mt-8 grid gap-4"><label className="text-sm font-medium text-neutral-300">URL de imagen (puedes agregarla después)<input value={imageUrl} onChange={(event) => setImageUrl(event.target.value)} placeholder="https://..." className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white placeholder:text-neutral-600" /></label><label className="text-sm font-medium text-neutral-300">Una descripción breve<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Qué se siente estar ahí." className="mt-2 min-h-28 w-full rounded-xl border border-white/15 bg-white/[.05] px-4 py-3 text-white placeholder:text-neutral-600" /></label></div></section>}
          {step === 5 && <section className="max-w-xl"><p className="text-sm font-medium text-[#b695ff]">06 — FINAL</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">Tu noche ya<br />tiene forma.</h1><div className="mt-7 rounded-2xl border border-[#9b6cff]/50 bg-[#9b6cff]/10 p-5"><p className="font-semibold">Se guardará como borrador.</p><p className="mt-2 text-sm leading-6 text-neutral-300">Podrás revisar accesos, ajustar detalles e invitar staff. Cuando estés listo, envías tu organización a revisión ANC para habilitar publicación y pagos.</p></div><button disabled={isSubmitting} className="mt-6 rounded-xl bg-[#9b6cff] px-5 py-3 text-sm font-bold text-black transition hover:bg-[#bda5ff] disabled:opacity-60">{isSubmitting ? "Guardando la noche…" : "Guardar esta noche"}</button></section>}
        </div>
        <footer className="flex items-center justify-between gap-4"><button type="button" onClick={previous} disabled={step === 0} className="text-sm font-semibold text-neutral-400 transition hover:text-white disabled:opacity-20">← Volver</button>{step < 5 && <button type="button" onClick={next} disabled={!canMove} className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-black transition hover:bg-[#bda5ff] disabled:opacity-30">{step === 4 ? "Ver mi evento" : "Continuar"} →</button>}</footer>
      </div>
      <aside className="relative overflow-hidden rounded-[1.5rem] border border-white/15 bg-gradient-to-b from-white/10 to-white/[.02] p-5"><div className="absolute inset-x-0 top-0 h-1 bg-[#9b6cff]" /><p className="text-[10px] font-bold tracking-[.24em] text-[#b695ff]">PREVIEW / EN VIVO</p>{imageUrl ? <img src={imageUrl} alt="Vista previa del evento" className="mt-5 aspect-[4/5] w-full rounded-xl object-cover grayscale" /> : <div className="mt-5 grid aspect-[4/5] place-items-end rounded-xl bg-[radial-gradient(circle_at_55%_25%,#9b6cff_0%,#2a1646_26%,#101010_63%)] p-5"><p className="w-full border-t border-white/30 pt-3 text-xs tracking-[.2em] text-white/80">{category.toUpperCase()} / ANC</p></div>}<div className="mt-5"><p className="text-xs uppercase tracking-[.2em] text-neutral-400">{category}</p><h2 className="mt-2 text-3xl font-black leading-[.92] tracking-[-.06em]">{title || "TU EVENTO"}</h2><p className="mt-4 text-sm text-neutral-300">{eventDate ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(eventDate)) : "Fecha por definir"}</p><p className="text-sm text-neutral-400">{venue || "Lugar por definir"}</p></div><div className="mt-6 border-t border-white/15 pt-4 text-xs text-neutral-400"><p>{accessMode === "presale" ? "PREVENTA + GENERAL" : "ACCESO DE PAGO"}</p><p className="mt-1">Borrador ANC · {step + 1}/6</p></div></aside>
    </div>
  </form>;
}

function TicketFields({ prefix, label }: { prefix: "presale" | "general"; label: string }) {
  return <div className="rounded-2xl border border-white/15 bg-white/[.03] p-4"><p className="text-sm font-semibold">{label}</p><label className="mt-3 block text-xs text-neutral-400">Valor<input required name={`${prefix}Price`} min="1" type="number" placeholder="12000" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-3 py-2 text-sm text-white" /></label><label className="mt-3 block text-xs text-neutral-400">Cupos<input required name={`${prefix}Capacity`} min="1" type="number" placeholder="100" className="mt-2 w-full rounded-xl border border-white/15 bg-white/[.05] px-3 py-2 text-sm text-white" /></label></div>;
}
