import OrganizerNav from "@/components/organizer-nav";
import { requireOrganizationManager } from "@/lib/organizer";
import { updateOrganizationProfile } from "../../actions";

export default async function OrganizerProfilePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { organization } = await requireOrganizationManager(slug);
  return <div><OrganizerNav slug={slug} /><h1 className="text-2xl font-bold">Perfil de organización</h1><form action={updateOrganizationProfile} className="mt-6 grid max-w-2xl gap-4 rounded-xl border border-neutral-200 p-5"><input type="hidden" name="slug" value={slug} /><label className="grid gap-1 text-sm font-medium">Nombre público<input disabled value={organization.name} className="rounded-lg border border-neutral-200 bg-neutral-100 px-3 py-2 text-sm text-neutral-500" /></label><label className="grid gap-1 text-sm font-medium">Descripción<textarea name="description" defaultValue={organization.description ?? ""} className="min-h-28 rounded-lg border border-neutral-300 px-3 py-2 text-sm" /></label><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Persona de contacto<input name="contactName" defaultValue={organization.contactName ?? ""} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm" /></label><label className="grid gap-1 text-sm font-medium">Teléfono<input name="contactPhone" defaultValue={organization.contactPhone ?? ""} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm" /></label><label className="grid gap-1 text-sm font-medium">Correo de soporte<input name="supportEmail" type="email" defaultValue={organization.supportEmail ?? ""} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm" /></label><label className="grid gap-1 text-sm font-medium">Sitio web<input name="websiteUrl" type="url" defaultValue={organization.websiteUrl ?? ""} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm" /></label></div><label className="grid gap-1 text-sm font-medium">URL de logo<input name="logoUrl" type="url" defaultValue={organization.logoUrl ?? ""} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm" /></label><button className="w-fit rounded-lg bg-neutral-950 px-4 py-2 text-sm font-semibold text-white">Guardar cambios</button></form></div>;
}
