import { desc, eq } from "drizzle-orm";
import OrganizerNav from "@/components/organizer-nav";
import { db } from "@/lib/db";
import { ambassadors, events } from "@/lib/db/schema";
import { requireOrganizationManager } from "@/lib/organizer";
import { createAmbassador } from "../../actions";

export default async function AmbassadorsPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { organization } = await requireOrganizationManager(slug);
  const organizerEvents = await db.select().from(events).where(eq(events.organizationId, organization.id));
  const rows = await db.select({ ambassador: ambassadors, eventTitle: events.title }).from(ambassadors).innerJoin(events, eq(events.id, ambassadors.eventId)).where(eq(events.organizationId, organization.id)).orderBy(desc(ambassadors.createdAt));
  return <div><OrganizerNav slug={slug} /><h1 className="text-2xl font-bold">Embajadores</h1><p className="mt-1 text-sm text-neutral-600">Cada embajador usa un código trazable. La comisión puede ser porcentaje, monto fijo o 0.</p><section className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{rows.length === 0 ? <p className="rounded-xl border border-dashed border-neutral-300 p-5 text-sm text-neutral-500">Aún no tienes embajadores.</p> : rows.map(({ ambassador, eventTitle }) => <article key={ambassador.id} className="rounded-xl border border-neutral-200 p-4"><p className="font-semibold">{ambassador.name} · <span className="font-mono">{ambassador.code}</span></p><p className="mt-1 text-sm text-neutral-500">{eventTitle} · {ambassador.commissionType === "none" ? "Sin comisión" : `${ambassador.commissionValue}${ambassador.commissionType === "percentage" ? "%" : " fijo"}`}</p></article>)}</div><form action={createAmbassador} className="h-fit rounded-xl border border-neutral-200 bg-neutral-50 p-5"><h2 className="font-semibold">Agregar embajador</h2><input type="hidden" name="slug" value={slug} /><div className="mt-4 grid gap-3"><select required name="eventId" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm"><option value="">Selecciona un evento</option>{organizerEvents.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select><input required name="name" placeholder="Nombre" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input name="email" type="email" placeholder="Correo (opcional)" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input required name="code" placeholder="Código del embajador" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><select name="commissionType" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm"><option value="none">Sin comisión</option><option value="percentage">Porcentaje</option><option value="fixed">Monto fijo</option></select><input name="commissionValue" type="number" min="0" step="0.01" defaultValue="0" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><button className="rounded-lg bg-neutral-950 px-4 py-2 text-sm font-semibold text-white">Guardar embajador</button></div></form></section></div>;
}
