import { desc, eq } from "drizzle-orm";
import OrganizerNav from "@/components/organizer-nav";
import { db } from "@/lib/db";
import { events } from "@/lib/db/schema";
import { requireOrganizationManager } from "@/lib/organizer";
import { createOrganizerEvent } from "../../actions";

export default async function OrganizerEventsPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { organization } = await requireOrganizationManager(slug);
  const organizerEvents = await db.select().from(events).where(eq(events.organizationId, organization.id)).orderBy(desc(events.eventDate));
  return <div><OrganizerNav slug={slug} /><h1 className="text-2xl font-bold">Eventos</h1><p className="mt-1 text-sm text-neutral-600">Todos los eventos comienzan en borrador. ANC habilita la primera publicación tras activar tu organización.</p><section className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{organizerEvents.length === 0 ? <p className="rounded-xl border border-dashed border-neutral-300 p-5 text-sm text-neutral-500">Aún no tienes eventos. Crea el primero desde este panel.</p> : organizerEvents.map((event) => <article key={event.id} className="rounded-xl border border-neutral-200 p-4"><div className="flex justify-between gap-4"><div><h2 className="font-semibold">{event.title}</h2><p className="mt-1 text-sm text-neutral-500">{new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(event.eventDate)} · {event.venue ?? "Lugar por definir"}</p></div><span className="text-xs font-semibold capitalize text-neutral-500">{event.status}</span></div></article>)}</div><form action={createOrganizerEvent} className="h-fit rounded-xl border border-neutral-200 bg-neutral-50 p-5"><h2 className="font-semibold">Crear evento</h2><input type="hidden" name="slug" value={slug} /><div className="mt-4 grid gap-3"><input required name="title" placeholder="Nombre del evento" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input required name="eventDate" type="datetime-local" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input name="venue" placeholder="Lugar o dirección" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><input name="category" placeholder="Categoría (música, deporte, etc.)" className="rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><textarea name="description" placeholder="Descripción corta" className="min-h-24 rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm" /><button className="rounded-lg bg-neutral-950 px-4 py-2 text-sm font-semibold text-white">Guardar borrador</button></div></form></section></div>;
}
