import { desc, eq } from "drizzle-orm";
import Link from "next/link";
import OrganizerNav from "@/components/organizer-nav";
import { db } from "@/lib/db";
import { events } from "@/lib/db/schema";
import { requireOrganizationManager } from "@/lib/organizer";
import { setOrganizerEventStatus } from "../../actions";

export default async function OrganizerEventsPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { organization } = await requireOrganizationManager(slug);
  const organizerEvents = await db.select().from(events).where(eq(events.organizationId, organization.id)).orderBy(desc(events.eventDate));
      const canPublish = organization.status === "active";
      return <div><OrganizerNav slug={slug} /><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Eventos</h1><p className="mt-1 text-sm text-neutral-600">Todos los eventos comienzan en borrador. ANC habilita la primera publicación tras activar tu organización.</p></div><Link href={`/dashboard/organizer/${slug}/events/new`} className="rounded-xl bg-neutral-950 px-4 py-2 text-sm font-semibold text-white">Crear la noche →</Link></div>{!canPublish && <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Tu organización está en estado <strong>{organization.status}</strong>. Puedes preparar eventos, pero ANC debe activarla antes de publicar y vender.</div>}<section className="mt-6 space-y-3">{organizerEvents.length === 0 ? <div className="rounded-xl border border-dashed border-neutral-300 p-5 text-sm text-neutral-500">Aún no tienes eventos. Abre “Crear la noche” para construir el primero sin formularios extensos.</div> : organizerEvents.map((event) => <article key={event.id} className="rounded-xl border border-neutral-200 p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">{event.title}</h2><p className="mt-1 text-sm text-neutral-500">{new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(event.eventDate)} · {event.venue ?? "Lugar por definir"}</p></div><div className="flex items-center gap-3"><span className="text-xs font-semibold capitalize text-neutral-500">{event.status}</span>{event.status !== "published" ? <form action={setOrganizerEventStatus}><input type="hidden" name="slug" value={slug} /><input type="hidden" name="eventId" value={event.id} /><input type="hidden" name="nextStatus" value="published" /><button disabled={!canPublish} className="rounded-lg bg-neutral-950 px-3 py-2 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Publicar</button></form> : <form action={setOrganizerEventStatus}><input type="hidden" name="slug" value={slug} /><input type="hidden" name="eventId" value={event.id} /><input type="hidden" name="nextStatus" value="draft" /><button className="rounded-lg border border-neutral-300 px-3 py-2 text-xs font-semibold text-neutral-700">Volver a borrador</button></form>}</div></div></article>)}</section></div>;
}
